# Generated by Selenium IDE
import pytest
from selenium.webdriver.chrome.options import Options
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestSmokeTest():
    def setup_method(self, method):
        options = Options()
        options.add_argument("--headless=new")  # run Chrome in headless mode
        self.driver = webdriver.Chrome(options=options)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_homePage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/index.html")
        self.driver.set_window_size(1181, 672)

        elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
        assert len(elements) > 0
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
        assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
        assert self.driver.title == "Teton Idaho CoC"
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 > p:nth-child(4)")
        assert len(elements) > 0
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 > p:nth-child(3)")
        assert len(elements) > 0

    def test_adminPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/admin.html")
        self.driver.set_window_size(1079, 672)

        self.driver.find_element(By.ID, "username").send_keys("admin")
        self.driver.find_element(By.ID, "password").send_keys("qwerty")
        self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
        assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."

    def test_directoryPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/directory.html")
        self.driver.set_window_size(1116, 672)

        self.driver.find_element(By.ID, "directory-grid").click()
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(4)")
        assert len(elements) > 0
        self.driver.find_element(By.ID, "directory-list").click()
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(4)")
        assert len(elements) > 0

    def test_joinPage(self):
        self.driver.get("http://127.0.0.1:5500/teton/1.6/join.html")
        self.driver.set_window_size(1073, 672)

        self.driver.find_element(By.NAME, "fname").send_keys("div")
        self.driver.find_element(By.NAME, "lname").send_keys("dee")
        self.driver.find_element(By.NAME, "bizname").send_keys("doe")
        self.driver.find_element(By.NAME, "biztitle").send_keys("miss")
        self.driver.find_element(By.NAME, "submit").click()
        elements = self.driver.find_elements(By.NAME, "email")
        assert len(elements) > 0
